"""Alter orders: add price, remove created_at

Revision ID: 54f0f6c63216
Revises: 5fff25ca7932
Create Date: 2025-07-14 16:53:11.441062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54f0f6c63216'
down_revision: Union[str, Sequence[str], None] = '5fff25ca7932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
